[build]
builder = "NIXPACKS"
buildCommand = "cd AgentK && pip install -r requirements.txt"

[deploy]
startCommand = "cd AgentK && uvicorn agent_kernel:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[envs]
PYTHON_VERSION = "3.11" 