[build]
builder = "NIXPACKS"
buildCommand = "pip install -r AgentK/requirements.txt"

[deploy]
startCommand = "cd AgentK && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 